### ISSUE TITLE
Add Tridge's geofence code to Copter

### ISSUE THREAD

**Issue by jabelone** [diydrones/ardupilot#2065] opened 2015-04-08 05:55 UTC
I was wondering if some kind soul would be able to add Tridge's geofence code to Copter?  Now that support for the APM2.x boards have been discontinued, what's stopping it?  (I would try, but sadly I I'm not good enough yet ;)  Thanks!

**Comment by jmachuca77** [comment] 2015-04-08 06:00
Hi, what geofence code are you referring to? Geofence is already supported in copter.

**Comment by jabelone** [comment] 2015-04-08 07:00
This one I believe - it supports a user definable polygon instead of just a circle with a set radius and height.  https://github.com/diydrones/ardupilot/blob/master/ArduPlane/geofence.pde

**Comment by rmackay9** [comment] 2015-04-08 22:38
Duplicate of this other issue so I'll close this one: https://github.com/diydrones/ardupilot/issues/1383

**Closed by rmackay9** 2015-04-08 22:38 UTC
