### ISSUE TITLE
Any plans to activate angle in waypoints?

### ISSUE THREAD

**Issue by jazzboy** [diydrones/ardupilot#500] opened 2013-08-17 03:39 UTC
Are there any plans to activate the angle option for a waypoint? Currently I have to add a CONDITION_YAW command but the operation would be so much better if the angle could be set right in the waypoint. It would cut the required command lines by half!

If any developers are reading this please let me know if this is in the works.

Cheers,

Andy

**Comment by gmorph** [comment] 2015-09-07 12:07
I'm going to close this as a duplicate of 
https://github.com/diydrones/ardupilot/issues/526
Even though this one was first the other has a LOT more information.
Thanks, Grant.

**Closed by gmorph** 2015-09-07 12:07 UTC
Labels: Enhancement
