### ISSUE TITLE
Copter: Oscillation in POSHOLD mode in recent master

### ISSUE THREAD

**Issue by claymation** [diydrones/ardupilot#1977] opened 2015-03-13 00:24 UTC
Somewhere between 9871b955866ed21e9c13b7f857222d17fa33aebd and 88ec13b10d913d72cdb0b24ba2e1244e6ed37734, a change was introduced that causes a ~4 Hz / ~3 degree oscillation in pitch and roll for copters flying in POSHOLD mode (at least in SITL). The vehicle maintains position, but wobbles, as if balancing on the tip of a pin.

![image](https://cloud.githubusercontent.com/assets/68641/6630988/b362bcb0-c8f5-11e4-97a0-233f88de83c6.png)

Steps to reproduce:

  * Check out 88ec13b10d913d72cdb0b24ba2e1244e6ed37734
  * `sim_vehicle.sh -w`
  * `level`
  * `sim_vehicle.sh -G --console --map --aircraft test`
  * `arm throttle`
  * `rc 3 1500`
  * Wait a couple seconds, until altitude ~25m
  * `mode poshold`

Observe oscillation.

/cc: @jschall

**Comment by rmackay9** [comment] 2015-03-13 11:57
Thanks for the report!
I think I've found and fixed the cause here.  I'm going to close this issue but will re-open if you say it's not fixed.
https://github.com/diydrones/ardupilot/commit/bb74b8dec86b074522438f2b83aff7ec5070d3be

![beforeafter2](https://cloud.githubusercontent.com/assets/1498098/6637915/79a334f4-c9c3-11e4-8269-9fe05c4352a5.png)

**Closed by rmackay9** 2015-03-13 11:57 UTC

**Comment by claymation** [comment] 2015-03-13 13:57
@rmackay9 thanks for looking into it, but if anything, it's worse now:

![image](https://cloud.githubusercontent.com/assets/68641/6639516/bbcac4e4-c966-11e4-9684-2951f6c32af3.png)

I can make a screencast of how I'm running the sim if that would help, but basically it's just:

  * `git checkout bb74b8d`
  * `make clean`
  * `sim_vehicle.sh -w`
  * `level`
  * `sim_vehicle.sh -G -L ATL --console --map --aircraft test` (where I've defined ATL to be near my house)
  * `arm throttle`
  * `rc 3 1500`
  * After ~1–2 secs:
  * `mode poshold`
  * `rc 3 1800`
  * Once we get to ~25m:
  * `rc 3 1500`

I can see the pitch and roll oscillating in the mavproxy console, which shows up in the graphs post-flight.

How can I help track it down?

**Comment by claymation** [comment] 2015-03-13 14:19
Here's another log from a flight where the oscillation didn't start right away:

![image](https://cloud.githubusercontent.com/assets/68641/6639952/650a0832-c96a-11e4-9806-ecebbe974838.png)

Is there a handy place I can dump the .BIN file for you?

**Comment by claymation** [comment] 2015-03-14 15:28
@rmackay9 I just ran into this on an older revision (), too, so I'm wondering if there's just something weird about my SITL setup. I noticed this in the docs:

> SITL can also be run within a virtual machine on Windows, Mac OSX or Linux, although this can cause timing issues and make it difficult to fly.

I'm running SITL on Ubuntu within a VMware Fusion VM with four cores allocated to it—do you suppose SITL just doesn't like running in my VM?
