### ISSUE TITLE
Copter: Dangerous flights when changed to ALT HOLD

### ISSUE THREAD

**Issue by vmayoral** [diydrones/ardupilot#2026] opened 2015-03-30 13:21 UTC
Following from #1989 we changed to EKF but have been experiencing similar behaviors:

>when taking off in ALT HOLD the copter suddenly gets height really aggressively:

![captura de pantalla 2015-03-30 a las 15 03 36](https://cloud.githubusercontent.com/assets/1375246/6896932/37de59b0-d6f0-11e4-9240-0d078f1b3b94.png)

Log available [here](https://github.com/erlerobot/logs/blob/13ba4dd5c7476665b8170c42b0efa74e157242a5/pxf/copter/30-3-2015/69.BIN).

Our guess so far is that the Kalman filter parameters are wrong or is not properly tuned.

**Comment by vmayoral** [comment] 2015-03-30 13:23
@R-Lefebvre, @rmackay9, @tridge not sure how to diagnose this problem.  Any thoughts on this matter are welcome.

**Comment by jschall** [comment] 2015-03-30 15:07
Paul and I have patches that need to be pulled in to fix this sort of thing.

**Comment by magicrub** [comment] 2015-03-30 15:27
It may be worthwhile to note that #2010
<https://github.com/diydrones/ardupilot/issues/2010> was a recent bug that
@Tridge just fixed that was causing the EKF to not initialize properly and
therefor were reverting to DCM.

**Comment by vmayoral** [comment] 2015-03-30 15:41
@jschall and @magicrub thanks for the comments.

We are flying with our code rebased on top of the latest commits. @jschall could you point out which are those commits?

Regards,

**Comment by vmayoral** [comment] 2015-03-31 14:28
The problem seemed to be vibration-related due to the frame we were using.

**Comment by vmayoral** [comment] 2015-03-31 14:50
**Update**: The problem does not seem to be vibration-related.

[Here](https://github.com/erlerobot/logs/blob/a9498522bf2336ce0e9c105232313368f2cae2f5/pxf/copter/31-3-2015/83.BIN) is a flight with 2 imus enabled (MPU6000 and MPU9250) where the copter, as soon as it changes to `ALT HOLD` mode gets height aggresively. Can anyone make any sense of it?

(this seems to be a continuation of #1989)

**Comment by rmackay9** [comment] 2015-03-31 16:38
This is really a duplicate of an existing issue so closing.
https://github.com/diydrones/ardupilot/issues/1009

**Closed by rmackay9** 2015-03-31 16:38 UTC
