### ISSUE TITLE
Airspeed Sensor problem failsafes

### ISSUE THREAD

**Issue by Jman841** [diydrones/ardupilot#3159] opened 2015-11-11 19:33 UTC
This is 2 features to possibly add.

1. If the plane is disarmed and/or see's airspeed values over a user defined value it should warn the pilot that the airspeed sensor may have problems. Or values lower than a user defined value.

2. Have an alternative RTL Mode that always uses no airspeed sensor. In the case the autopilot reports the airspeed sensor is malfunctioning or is showing values that it should never see, have a second RTL mode that turns off the use of the airspeed sensor and uses the airspeed estimates to get back safely.

We had issues with an airspeed sensor going wild and luckily saw it before taking off (Speeds over 100 m/s being reported on the ground without the plane armed), but, it would be nice to know if something happens to the airspeed sensor there is an option to get it back to home without the need of the airspeed sensor.

**Comment by magicrub** [comment] 2015-11-11 20:26
The proper solution is not to switch to internal airspeed calc then RTL, it is to handle faulty sensor hardware. Duplicate of https://github.com/diydrones/ardupilot/issues/1628

**Closed by magicrub** 2015-11-11 20:26 UTC
