### ISSUE TITLE
Unable to arm with Spektrum satellite receiver - channels mapping issues

### ISSUE THREAD

**Issue by nikivan1** [diydrones/ardupilot#2900] opened 2015-09-25 08:23 UTC
Plane v3.4.0. Steps to reproduce.
- Pair Spekrum DX8 radio with the receiver (including the satellite receiver)
- install Spekrum satellite receiver on Pixhawk
- change RCMAP to Pitch - 3, Roll - 2, Throttle - 1, Yaw - 4 to match Spekrum channels order
- calibrate radio
Mission planner shows ch3in moving when moving throttle (Flight Data / Status screen).

Issue 1 - Mission planner incorrectly shows Throttle & Pitch channels (they appear swapped) in the Initial Setup / Radio Calibration screen

Issue 2 - Unable to arm by moving the Rudder to Right & Throttle at minimum. However, if I move Roll stick to right (together with right Rudder) the board arms. 

Issue 3 - Switching to FBWA on the ground turns on the motor even if not armed.

**Comment by WickedShell** [comment] 2016-02-09 07:28
Closing as this is a support issue and I am unable to reproduce this with a DX7 and satellite. The forums are meant for this type of support issue.

You're RCMAP's sound incorrect though, I didn't need to do any RCMAP'ing to get the right behavior with a DX7 black and DSM x reciever:
RCMAP_PITCH 2
RCMAP_ROLL 1
RCMAP_THROTTLE 3
RCMAP_YAW 4

**Closed by WickedShell** 2016-02-09 07:28 UTC
