### ISSUE TITLE
Pixhawk and EMAX ESC

### ISSUE THREAD

**Issue by All4U** [diydrones/ardupilot#2094] opened 2015-04-12 09:18 UTC
I wonder the need of raising an issue...about Emax ESC and the Pixhawk:
- When I plug the ESC direct to X8R receiver, power up, hearing some tone from motor, raise up the throttle and the motor spin: OK
- When I plug the ESC through mainout of Pixhawk, after Arming the motor, the ESC seem no wake up and the motor didnt spin! (I can see the output value via APM planner when throttle is raise up)
- I did some gooogle and see that many of us faced with this problem, they guess the causes may lied in hardware like Voltage level (pixhawk output) or in the Firmware like the required pulse to wakeup the Emax ESC before it timeout, etc....but actually, no such good solution...
So, please here any one had come over this can share the solution?

Best regards,

**Comment by R-Lefebvre** [comment] 2015-04-12 13:23
This is not an APM software issue, nor is it an issue with the Pixhawk hardware.  This is an issue with the Emax ESC.

**Comment by rmackay9** [comment] 2015-07-22 05:05
I've reopened this issue at least as a place holder.  The issue appears to be that the Emax ESC gets confused by the high signal that the Pixhawk outputs at startup.  The APM2 for example outputs a low signal on startup.

I'm afraid it's a fairly low level change in the PX4Firmware layer which I'm not personally going to be able to resolve I think.  Perhaps another developer can look into it or maybe the EMAX ESC people can resolve the issue on their side.

There's a related issue to the Parachute here.
https://github.com/diydrones/ardupilot/issues/1239

**Comment by alduxvm** [comment] 2015-07-28 09:23
To solve this issue, remove the 2 resistors marked in the picture and that will be it, Randy and Robert were right, this is a ESC hardware issue... 

![12a](https://cloud.githubusercontent.com/assets/8823379/8927893/9529a27a-3512-11e5-8eb3-77299069455c.jpg)

**Comment by magicrub** [comment] 2015-07-28 13:56
The two components in your circle look like a resistor and a capacitor, not
two resistors.

**Comment by alduxvm** [comment] 2015-07-28 13:58
Yes, remove those two components...

**Comment by magicrub** [comment] 2015-07-28 14:01
Solved, and also a duplicate of https://github.com/diydrones/ardupilot/issues/2033

**Closed by magicrub** 2015-07-28 14:01 UTC
Labels: PX4, wontfix

**Comment by estechnical** [comment] 2015-12-02 23:12
Hi, I thought I should follow up on this issue as it seems people are modifying their EMax ESCs...

I have modified mine and they run fine now - I removed the resistor and capacitor after finding the signal level was very low and getting the meter out.

After making this modification however I would now suggest an extra step/improvement to the solution as this modification makes the ESCs no longer work with the EMax program card. To make the program card work again, it is necessary to add a 10k pull down resistor to the signal so that the bidirectional serial communication can work with the program card.

Also, just an observation but possibly important, without the pull down resistor the signal line is left electrically floating if the signal lead is unplugged and is only connected to the pin of the MCU in the ESC.

The best solution to this is:
replace the bottom resistor (circled in the photo above) with a 10k resistor
*and*
replace the resistor immediately above the circled components with a low value eg 100R or 220R.
The capacitor should also be removed as per the suggestion above.

**Comment by alireza-manzoori** [comment] 2016-08-05 08:13
Interesting update on the EMAX ESC issue with Pixhawk: **The issue is apparently resolved in the new generation of EMAX Simon ESCs!**

I was making a new quadrotor and again decided to use Emax Simon ESCs despite their compatibility issue with Pixhawk (as they are by far the cheapest and most available ESC in the local stores here). Before ripping the heat shrink on the ESCs to remove the resistor and capacitor as I had done before, I decided to test them. So I attached them to Pixhawk and the motors started spinning right away!

I think EMAX has modified the ESCs to resolve this problem finally, but maybe it's still too soon to jump to this conclusion. I have tested Emax Simon 20A ESCs with Pixhawk, Copter Firmware V3.2 & 3.3 both worked fine.

**Comment by Steadyspike** [comment] 2017-10-01 00:22
I have same problem with Emax Lightning 30A BLHeli and Pixhawk. Does someone know which components should I replace? Find attached a photo.

![emax_a](https://user-images.githubusercontent.com/24420713/31050593-63548890-a64f-11e7-8d35-4d954cf23bbe.jpg)
![emax_b](https://user-images.githubusercontent.com/24420713/31050594-6358de0e-a64f-11e7-811a-566a1d8937f4.jpg)

**Comment by 9friday** [comment] 2020-09-15 16:42
I want to use the Emax BLHeli Series 30A ESC(https://emaxmodel.com/catalog/product/view/id/101/s/blheli-series-30a-esc/) with the Pixhawk. 
Is the issue with Pixhawk resolved for all EMAX ESCs or only specific models?
This link(https://ardupilot.org/copter/docs/connect-escs-and-motors.html) still mentions that Pixhawk has an issue with EMAX ESCs.

Any help would be appreciated.
Regards.

**Comment by rmackay9** [comment] 2020-09-15 23:36
@9friday, It seems that the underlying issue is with the ESC itself.  I don't think we have heard if the manufacturer has fixed the issue.  If you do buy them please tell us if they seem to work or not.

**Comment by mbuzdalov** [comment] 2021-01-24 02:36
Just for an information, I can confirm that ESCs called "Emax Formula 45A BLHeli32 32Bit" work quite well with Pixhawk.

**Comment by mateoc6** [comment] 2022-03-30 00:28
> Just for information, I can confirm that ESCs called "Emax Formula 45A BLHeli32 32Bit" work quite well with Pixhawk.

Hi Mbuzdalov,
I recently purchased the exact same ESCs for my drone and couldn't seem to get my motors running through them. I was wondering what you did when connecting it to the cube/pixhawk. I currently have the white wire/signal wire connected to signal on the main out signal pin. Then the same thing for the ground wire.

**Comment by rmackay9** [comment] 2022-03-30 00:33
@mateoc6, maybe the safety switch is on?  Try setting BRD_SAFETYENABLE = 0.  Just a random guess..

**Comment by mateoc6** [comment] 2022-03-30 00:36
> @mateoc6, maybe the safety switch is on? Try setting BRD_SAFETYENABLE = 0. Just a random guess..

I will check that option, that's a good possibility. Thank you

**Comment by mateoc6** [comment] 2022-03-31 16:04
> @mateoc6, maybe the safety switch is on? Try setting BRD_SAFETYENABLE = 0. Just a random guess..

I took a look at the setting and it was already set to 0. I will probably search the ardupilot page to see if anyone has posted this before, if not start a new post about it.

**Comment by mituritsyn** [comment] 2022-08-22 11:18
> 

I've faced similar issue with another ESCs. This is due to low resistance on esc signal pin lead to PWM amplitude lowering so ESC couldn't recognise it
