### ISSUE TITLE
Altitudes in the GLOBAL_POSITION_INT message

### ISSUE THREAD

**Issue by dongfang** [diydrones/ardupilot#663] opened 2013-11-06 11:30 UTC
ArduPlane and ArduCopter generally use current_loc.alt for flight and navigation. This is an ASL altitude derived from a combination of GPS and baro sources. It is generally much more precise for small changes than pure GPS altitude,

The GLOBAL_POSITION_INT message from ArduPlane and ArduCopter has two altitudes, absolute (ASL) and relative to ground.

Strangely, the absolute altitude is not current_loc.alt but g_gps->altitude_cm. This has the implications:
1) It is not a constant difference above the relative altitude in the same message (which IS derived from current_loc.alt) but may vary relative to it
2) The only message containing current_loc.alt is VFR_HUD. If we need to know the altitude the airplane or copter is actually using, we need to subscribe to VFR_HUD. Really, the GLOBAL_POSITION_INT message is for that kind of thing.

I suggest using current_loc.alt instead of g_gps-> altitude_cm in the GLOBAL_POSITION_INT message. This should not be able to cause any disasters in ground station software that is not prepared for the change - both are ASL altitudes but current_loc.alt is more relevant and less noisy. For purposes where pure GPS alt is needed there is still the RAW_GPS message.

**Comment by gmorph** [comment] 2015-09-07 12:16
This is a duplicate of 
https://github.com/diydrones/ardupilot/issues/327
Closing.  Any objections please let me know.
Thanks, Grant.

**Closed by gmorph** 2015-09-07 12:16 UTC
