### ISSUE TITLE
Bad AHRS warning too strict?

### ISSUE THREAD

**Issue by GrahamDyer** [diydrones/ardupilot#3179] opened 2015-11-14 19:31 UTC
A number of people (including myself) are getting the Bad AHRS warning on our Pixhawk or AUAV-X2 boards. Are the checks for this perhaps a little too strict?
Ref: http://diydrones.com/forum/topics/bad-ahrs

**Comment by magicrub** [comment] 2015-11-14 21:33
Are you, and the others, running the latest release? It's much better now.

**Comment by R-Lefebvre** [comment] 2015-11-15 01:07
I get it way too frequently too.

**Comment by GrahamDyer** [comment] 2015-11-15 06:53
Running AP 3.4 and AC 3.3, getting on both

**Comment by severinleuenberger** [comment] 2015-11-15 13:38
Running APM 3.4 plane and see it to often as well

**Comment by OXINARF** [comment] 2015-11-15 18:09
Maybe related to #3171?

**Comment by rmackay9** [comment] 2015-11-16 00:46
Yes, I suspect @OXINARF is right.  Maybe we should add this to the list for a Copter-3.3.2 patch release.

**Comment by magicrub** [comment] 2015-11-16 00:52
And plane v3.4.1

**Comment by R-Lefebvre** [comment] 2015-11-16 03:48
But if I'm reading it right, according to Paul this was already fixed in 3.3.1?

**Comment by OXINARF** [comment] 2015-11-16 03:52
No, it was fixed after the 3.3.1 release.

**Comment by R-Lefebvre** [comment] 2015-11-16 03:59
Ah, I see.  I read "since the release" the wrong way.

**Comment by OXINARF** [comment] 2015-11-16 04:34
To supply more info: the commit that Paul said that fixed it should be 59df23b, which came from the PR #3101

**Comment by mtcl** [comment] 2015-11-18 02:29
Same issue here, I am getting Bad AHRS error also, this happened so much while flying hat it made the copter crash. Its a brand new Pixhawk's second flight.

**Comment by rmackay9** [comment] 2015-11-18 03:09
@mtcl, this should cause crashes so it would be good to provide a dataflash log.

**Comment by Zanquar** [comment] 2016-01-07 05:47
calibrate Accel again and again, and then, the warning can be solved

**Comment by magicrub** [comment] 2016-01-07 06:08
Not all IMUs are created equal (mfgr error), nor are the calibrations (human error). I've added a param "INS_ACCTHRESH" to help loosen it for mfgr type error. https://github.com/diydrones/ardupilot/pull/3364
Is that good enough to close this or is more work needed to fix the root cause?

Also, EKF2 is more tolerant (it can compensate faster/better) so the thresholds could be loosened when EKF2 is used.

**Comment by courierdude** [comment] 2016-02-04 07:23
Has anybody found a solution to BAD AHRS? Please, I'm begging you. This is my third day of re installing firmware, doing ACCEL calibrations, GPS calibrations, Googling, and generally pulling my hair out.

**Comment by magicrub** [comment] 2016-02-04 07:27
fixed with https://github.com/diydrones/ardupilot/pull/3364 on Plane v3.5.0

**Closed by magicrub** 2016-02-04 07:27 UTC
