### ISSUE TITLE
Mavlink on serial 5

### ISSUE THREAD

**Issue by mpd79** [diydrones/ardupilot#2739] opened 2015-08-23 10:47 UTC
Hi could I raise an enhancement? I have a pixhawk with Frsky telemetry on S1, 3Dr radio GCS on S2, GPS on S3 & S4. This means I have run out of ports for a storm32 Mavlink gimbal. Could S5 be configurable for this function? Cheers, Mike

**Comment by rmackay9** [comment] 2015-08-24 02:21
Duplicate of this existing issue: https://github.com/diydrones/ardupilot/issues/2552

**Closed by rmackay9** 2015-08-24 02:21 UTC
Labels: Duplicate
