### ISSUE TITLE
Copter: reduce wobbles while descending by linearizing throttle output

### ISSUE THREAD

**Issue by lion13ch** [diydrones/ardupilot#1244] opened 2014-07-21 04:21 UTC
The best practice to make copter more stable at fast descent is to rise Rate D (roll/pitch). But rising Rate D make copter to oscilate at hi throttle rates and posible to make problem at hi speed flight. So is It possible to make Rate D different at hight and low trottle condition ? 
It may be curve, liner start-and settings or just corrections of PID algorithm...

**Comment by rmackay9** [comment] 2015-03-16 06:00
Leonard's new thrust curve is in master and will go out with AC3.3.  This apparently gets rid of the over-tuned feeling when throttle is at full and should increase the gains when throttle is low which should reduce the wobbles during descent.
This needs to be tested but I'm closing this issue at least for now.  Closing the issue is the way we record that we think we've resolved an issue.  Then we re-open if we find we actually haven't.

**Closed by rmackay9** 2015-03-16 06:00 UTC
Labels: ArduCopter, enhancement
