### ISSUE TITLE
GPS_UBLOX : We are not reading the HDOP value from the Ublox

### ISSUE THREAD

**Issue by ghost** [diydrones/ardupilot#462] opened 2013-07-26 16:41 UTC
Inside AP_GPS_UBLOX.cpp is hdop = position DOP  (PDOP)

AP_GPS_UBLOX.cpp
   linie 264         hdop = _buffer.solution.position_DOP;

PDOP value i read in U-Blox Ucenter software is same as HDOP in mission planner 1.2.62,   HDOP is 40-50% lower in ublox Ucenter.

Read  this
http://diydrones.com/forum/topics/arducopter-3-0-1-released?commentId=705844%3AComment%3A1348017&xg_source=msg_com_forum

**Comment by MJBeaubien** [comment] 2015-05-20 21:18
I hope this issue gets resolved soon...

**Comment by TheQuestor** [comment] 2015-06-23 21:38
Still reports PDOP instead of HDOP. It's only a matter of "1" letter, how hard can it be to change the 1 letter in mission planner to say "P"DOP

**Comment by magicrub** [comment] 2015-06-23 21:41
The best part about open-source software is you can fix it yourself! It's
just "1" letter...

**Comment by andyp1per** [comment] 2015-06-27 13:20
So the issue is that the other drivers actually report hDOP. So I think the correct fix is to do the same.
https://github.com/diydrones/ardupilot/pull/2462 fixes this.

**Comment by gmorph** [comment] 2015-09-07 12:00
Closing as its fixed.  If anyone objects please let me know.
Thanks, Grant.

**Closed by gmorph** 2015-09-07 12:00 UTC
