### ISSUE TITLE
why STIL cant work???

### ISSUE THREAD

**Issue by ahmedelbacksawy** [diydrones/ardupilot#3329] opened 2015-12-11 23:03 UTC
i done more than 10 times the steps from that link http://dev.ardupilot.com/wiki/sitl-native-on-windows for SITL with out any use .... all times with the same problem on that line (Download and make ArduPilot)
what can i do ??? i need it very fast for my project to test my code :\

**Comment by magicrub** [comment] 2015-12-12 00:24
Duplicate of https://github.com/diydrones/ardupilot/issues/3269

**Comment by rmackay9** [comment] 2015-12-12 00:24
@ahmedelbacksawy, I personally always run SITL within a VM
http://dev.ardupilot.com/wiki/setting-up-sitl-on-windows/

**Closed** 2015-12-12 00:24 UTC

**Comment by ahmedelbacksawy** [comment] 2015-12-13 01:44
@rmackay9  is that work fine ???

**Comment by rmackay9** [comment] 2015-12-14 01:09
@ahmedelbacksawy, yes, it works a-ok.

**Comment by magicrub** [comment] 2015-12-14 02:14
I think most devs use SITL on Linux or Linux with VM.
