### ISSUE TITLE
new flightmode "autostart" for plane (climb to 50m in start direction, then loiter)

### ISSUE THREAD

**Issue by severinleuenberger** [diydrones/ardupilot#3492] opened 2016-01-12 18:29 UTC
It would be great, if there would be a flight mode like "autostart" as it is provided by many flight controllers like MFD (http://www.myflydream.com/download/MFD_AP_en.pdf) and of course like the new Parrot Disco: https://www.youtube.com/watch?v=1w1HIwrbWn4

The logic should be - fly to a specified high e.g. 50m above ground in a straight line following the direction the nose pointed on launch and then loiter there until further commands are received. 
Loiter of course with the same logic like the existing loiter mode with WP_LOITER_RAD and with half the pitch defined by TECS_PITCH_MAX (e.g. if TECS_PITCH_MAX is set to 45, then it would climb with 22.5. The desired high to loiter should be set to 50m above starting point, what is a good value for most planes, and could be adjusted by using ALT_HOLD_RTL. 
Throttle should be set with TKOFF_THR_MAX

This would not only be a nice feature. It could be a cool  improvement for bigger fixed-wing-drones who are difficult to handlaunch by not having a second person helping to launch the drone!

**Comment by WickedShell** [comment] 2016-01-12 18:52
Closting as duplicate of #2811 

Similar comments as there, this is all easily doable right now with a mission. Otherwise the other issue is open to track this.

**Closed by WickedShell** 2016-01-12 18:52 UTC

**Comment by severinleuenberger** [comment] 2016-01-12 19:13
thanks!
